
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATA DATE INSERT LAST PICK RANGE SEMICOLONstatement : INSERT DATA SEMICOLONstatement : PICK LAST SEMICOLONstatement : PICK RANGE DATE DATE SEMICOLON'
    
_lr_action_items = {'INSERT':([0,],[2,]),'PICK':([0,],[3,]),'$end':([1,7,8,11,],[0,-1,-2,-3,]),'DATA':([2,],[4,]),'LAST':([3,],[5,]),'RANGE':([3,],[6,]),'SEMICOLON':([4,5,10,],[7,8,11,]),'DATE':([6,9,],[9,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> INSERT DATA SEMICOLON','statement',3,'p_statement_insert','main.py',86),
  ('statement -> PICK LAST SEMICOLON','statement',3,'p_statement_pick_last','main.py',93),
  ('statement -> PICK RANGE DATE DATE SEMICOLON','statement',5,'p_statement_pick_range','main.py',101),
]
